### ISSUE TITLE
Realm LiveData has given null pointer exception

### ISSUE THREAD

**Issue by gelbertgel** [Zhuinden/realm-monarchy#23] opened 2018-10-03 08:47 UTC
It has given this error sometimes.

```

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void android.arch.lifecycle.m.a(java.lang.Object)' on a null object reference
       at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
       at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
       at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
       at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
       at android.arch.lifecycle.LiveData$1.run(LiveData.java:87)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6518)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

and notifyItemChanges aren't working sometimes.

**Comment by Zhuinden** [comment] 2018-10-03 09:30
Does it have like, the *head* of this message?

Because there should be something before `considerNotify`

**Comment by gelbertgel** [comment] 2018-10-03 11:25
Pardon quotes slipped at question.

**Comment by Zhuinden** [comment] 2018-10-03 13:47
> observer.mObserver.onChanged((T) mData);

Wow. uh. Do you use the newly added `forceOpen`?

Because the observer shouldn't arbitrarily go missing.

**Comment by gelbertgel** [comment] 2018-10-03 16:30
No I'm doing your same, not changing anywhere

**Comment by Zhuinden** [comment] 2018-10-03 16:54
it says this happens if you don't retain the LiveData, and you observe it, and then it is eventually lost and GCed.

This is not specific to Realm-Monarchy, apparently this happens also with Room, see https://stackoverflow.com/a/48546968/2413303

**Comment by Zhuinden** [comment] 2018-10-04 00:11
This line is in the AAC, it's kinda like as if the registered observer "disappeared", which should not happen.

I don't arbitrarily discard observers registered on any LiveData returned from Monarchy, so I'd need a minimal reproducible sample to debug this and see wtf is going on. :|

It is called in `at android.os.Looper.loop(Looper.java:164)` which means it happens in `postValue`. That should not have this sort of problem.

**Comment by gelbertgel** [comment] 2018-10-10 08:56
please add `DiffResults` to `CopiedLiveResults` . I am trying to instead of `ManagedLiveResults`.

**Comment by Zhuinden** [comment] 2018-10-10 09:25
If you can use `CopiedLiveResults`, then you can ditch the custom diff stuff and you can use `ListAdapter` instead.

**Comment by gelbertgel** [comment] 2018-10-10 11:40
I guess that mixed activities realms.  When activity needs to realm, called `getRealm()` function. when activity is called `onStop()` , `closeRealm` function is called. But first activity `onStop` function overlapped second activity `getRealm()` function. So gave this error:

`This Realm instance has already been closed, making it unusable.`

MomActivity{

 Realm realm;
 public Realm getRealm() {

        if (!getRealmManager().checkRealm(realm)) {
            realm = getRealmManager().open();
        }

        return realm;
    }

    public void setRealm(Realm realm) {

        //getRealmManager().close(this.realm);
        this.realm = realm;
    }

    public void closeRealm() {

        if (realmManager != null) {
            realmManager.close(realm);
        }
    }

    public RealmManager getRealmManager() {

        if (realmManager == null) {
            realmManager = new RealmManager.Builder().build();
        }

        return realmManager;
    }

    public void closeInstanceRealm() {

        if (realmManager != null) {
            realmManager.close();
        }
    }

}

**Comment by gelbertgel** [comment] 2018-10-10 11:56
Ok. I guess that find error. Some activities aren't calling `onPause` function and causing that not calling `closeRealm`.

**Comment by Zhuinden** [comment] 2018-10-10 12:02
`Lifecycle` should manage this automatically, which is why you `observe(lifecycleOwner, ` in the first place.

**Comment by gelbertgel** [comment] 2018-10-10 12:07
Yes there is no problem with it. I moved `closeRealm` function  from `onPause` to `onStop`. I don't know if the error goes.

**Comment by Zhuinden** [comment] 2018-10-10 12:12
Please note that Monarchy already manages open-closing Realm via `onActive`/`onInactive`, which is driven by `onStart`/`onStop`.

**Comment by gelbertgel** [comment] 2018-10-10 12:31
In that case the error is not caused by it and I can not find that :(

**Comment by Zhuinden** [comment] 2018-10-10 13:32
I have honestly no idea why the "observer wrapper"'s observer is null inside the LiveData.

I'm not doing anything specific beyond exposing LiveData.

However it's a more tricky thing that you said "sometimes notifications don't work". That *might* be caused by closing the Realm in onStop and then re-opening in onStart.

**Comment by gelbertgel** [comment] 2018-10-10 15:03
Ok last question:

All realm operations which except adapter are using `realmManager's getRealm()` function and activity `onStop` function is calling `closeInstanceRealm`. Is it true?


Activity:

 ```
     public Realm getRealm(){
        return getRealmManager().open();
    }

     public RealmManager getRealmManager() {

        if (realmManager == null) {
            realmManager = new RealmManager.Builder().build();
        }

        return realmManager;
      }

      public void closeRealm() {

        if (realmManager != null) {
            realmManager.close();
        }
    }

      @Override
      protected void onStop() {
        super.onStop();

        closeRealm();
    }

```

RealmManager:

```
    
    private final ThreadLocal<Realm> localRealms = new ThreadLocal<>();

    public Realm open() {

        Realm realm = Realm.getInstance(realmConfiguration);

        if (!checkRealm(localRealms.get())) {
            localRealms.set(realm);
        }

        realm.refresh();

        return realm;
    }

    public Realm getLocalInstance() {

        Realm realm = localRealms.get();

        if (!checkRealm(realm)) {
            realm = open();
        }

        realm.refresh();

        return realm;
    }

    public void close(Realm realm) {

        if (!checkRealm(realm)) {
            return;
        }

        realm.close();
        controlLocalInstanceCount();
    }

    public void close() {

        Realm realm = localRealms.get();
        close(realm);
    }

    public boolean checkRealm(Realm realm) {
        return realm != null && !realm.isClosed();
    }
```

**Comment by Zhuinden** [comment] 2018-10-10 15:31
I mean, if you're using Monarchy, then you generally don't even need this thing.

**Closed as completed** 2019-10-21 04:11 UTC
Labels: reproduction-required
